export const MONTHLY_REVIEW_ENGINE_VERSION="1.0.0",MONTHLY_REVIEW_RULESET_VERSION="2026.08";
export type MonthlyReviewInput={goal?:string;currentWeightLb?:number;priorWeightLb?:number;waistIn?:number;priorWaistIn?:number;workoutAdherence:number;nutritionAdherence:number;trainingPerformance:"declining"|"stable"|"improving";energy:number;recovery:number;sleep:number;hunger:number;pain?:boolean;photoSetCount?:number;completePhotoViews?:number};
export type MonthlyAction={type:string;scope:string;beforeState:Record<string,unknown>;afterState:Record<string,unknown>;reasonCodes:string[];plainLanguageReason:string};
const label=(score:number)=>score<=2?"low":score>=4?"strong":"adequate";
export function assessMonth(input:MonthlyReviewInput,current:{calories?:number;cardioSessions?:number}={}){
 const weightDelta=input.currentWeightLb!==undefined&&input.priorWeightLb!==undefined?Math.round((input.currentWeightLb-input.priorWeightLb)*10)/10:null,waistDelta=input.waistIn!==undefined&&input.priorWaistIn!==undefined?Math.round((input.waistIn-input.priorWaistIn)*10)/10:null,adherence=Math.min(input.workoutAdherence,input.nutritionAdherence),recovery=Math.round((input.energy+input.recovery+input.sleep)/3*10)/10,visualConfidence=(input.photoSetCount??0)>=2&&(input.completePhotoViews??0)>=3?"clear":(input.photoSetCount??0)>=2?"unclear":"insufficient";let overall="on_track",actions:MonthlyAction[]=[];const reasons:string[]=[];
 if(input.pain){overall="safety_attention";reasons.push("PAIN_REPORTED","PLAN_CHANGE_BLOCKED");}
 else if(adherence<70){overall="adherence_limited";reasons.push("ADHERENCE_LIMITS_INFERENCE","PLAN_STABILITY");}
 else if(recovery<2.5){overall="recovery_limited";reasons.push("RECOVERY_SIGNAL_REPEATED");actions=[{type:"deload_recovery",scope:"training",beforeState:{trainingDemand:"current"},afterState:{trainingDemand:"reduced_for_one_week"},reasonCodes:["RECOVERY_SIGNAL_REPEATED","MINIMUM_EFFECTIVE_CHANGE"],plainLanguageReason:"Recovery has been consistently low. Reduce training demand for one week without cutting calories or adding cardio."}]}
 else if(input.goal==="lose_fat"&&weightDelta!==null&&weightDelta>-0.5&&input.nutritionAdherence>=80&&current.calories){overall="adjustment_warranted";reasons.push("FAT_LOSS_TREND_BELOW_RANGE");actions=[{type:"calorie_change",scope:"nutrition",beforeState:{calories:current.calories},afterState:{calories:Math.max(1400,current.calories-150)},reasonCodes:["FAT_LOSS_TREND_BELOW_RANGE","MINIMUM_EFFECTIVE_CHANGE"],plainLanguageReason:"Adherence is strong but the four-week weight trend is below the planned range. A conservative 150-calorie adjustment is appropriate."}]}
 else reasons.push(weightDelta===null?"INSUFFICIENT_WEIGHT_TREND":"TREND_WITHIN_EXPECTATION","PLAN_STABILITY");
 const noChange=actions.length===0;
 return{overall_status:overall,body_composition_status:weightDelta===null&&waistDelta===null?"insufficient_data":"trend_observed",training_status:input.trainingPerformance,nutrition_status:input.nutritionAdherence>=80?"consistent":input.nutritionAdherence>=60?"mixed":"limited",recovery_status:label(recovery),adherence_status:adherence>=80?"strong":adherence>=70?"adequate":"limited",visual_change_confidence:visualConfidence,recommended_actions:actions,reason_codes:reasons,summary:noChange?(overall==="safety_attention"?"Your report needs safety attention before any plan changes are considered.":overall==="adherence_limited"?"There is not enough consistent execution to judge the plan. Keep targets unchanged and make the current plan easier to follow.":"Your current evidence does not justify changing training or nutrition this month. Keep the plan steady."):`I recommend ${actions.length} measured ${actions.length===1?"change":"changes"} based on the full month of evidence.`};
}
export function validateMonthlyAction(action:MonthlyAction){if(action.type==="calorie_change"){const calories=Number(action.afterState.calories);return Number.isFinite(calories)&&calories>=1400&&calories<=6000}return action.type==="deload_recovery"||action.type==="maintain_plan";}
