import { redirect } from "next/navigation";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { hasEditorialAccess } from "@/lib/editorial/access";

const stages = ["social_landing_view","assessment_start","assessment_question_viewed:q5","assessment_question_viewed:q10","assessment_question_viewed:q20","assessment_complete","assessment_preview_view","signup_complete","checkout_start","subscription_complete"] as const;
const labels = ["Visitors","Starts","Q5","Q10","Q20","Complete","Preview","Account","Checkout","Paid"];
type Params={days?:string;source?:string;medium?:string;campaign?:string;device?:string;browser?:string;variant?:string;version?:string;include_internal?:string};
type Row={id:string;event_name:string;source:string;medium:string|null;campaign:string|null;device:string;browser:string;landing_variant:string;anonymous_session_id:string|null;user_id:string|null;properties:Record<string,unknown>|null;created_at:string;route:string|null;app_version:string|null;bot_signal:boolean};
const cutoffIso=(days:number)=>new Date(Date.now()-days*86400000).toISOString();
const actor=(row:Row)=>row.user_id??row.anonymous_session_id??row.id;
function matchesStage(row:Row,stage:string){const [name,q]=stage.split(":");return row.event_name===name&&(!q||Number(row.properties?.question_number)>=Number(q.slice(1)));}
function unique(rows:Row[],stage:string){return new Set(rows.filter(row=>matchesStage(row,stage)).map(actor)).size;}
function median(values:number[]){if(!values.length)return 0;const sorted=[...values].sort((a,b)=>a-b),mid=Math.floor(sorted.length/2);return Math.round(sorted.length%2?sorted[mid]:(sorted[mid-1]+sorted[mid])/2);}

export default async function AcquisitionReport({searchParams}:{searchParams:Promise<Params>}){
  const server=await createSupabaseServerClient(),{data:{user}}=server?await server.auth.getUser():{data:{user:null}};
  if(!await hasEditorialAccess(user))redirect("/app");
  const q=await searchParams,days=Math.min(365,Math.max(1,Number(q.days??30))),admin=createSupabaseAdminClient();
  if(!admin)return <main className="admin-funnel"><h1>Analytics unavailable</h1><p>The server analytics connection is not configured.</p></main>;
  let query=admin.from("social_funnel_events").select("id,event_name,source,medium,campaign,device,browser,landing_variant,anonymous_session_id,user_id,properties,created_at,route,app_version,bot_signal").gte("created_at",cutoffIso(days)).order("created_at",{ascending:false}).limit(50000);
  if(q.source)query=query.eq("source",q.source);if(q.medium)query=query.eq("medium",q.medium);if(q.campaign)query=query.eq("campaign",q.campaign);if(q.device)query=query.eq("device",q.device);if(q.browser)query=query.eq("browser",q.browser);if(q.variant)query=query.eq("landing_variant",q.variant);if(q.version)query=query.eq("app_version",q.version);
  const [{data,error},{data:internalProfiles}]=await Promise.all([query,admin.from("profiles").select("user_id,is_internal,is_test_user").or("is_internal.eq.true,is_test_user.eq.true")]);
  if(error)return <main className="admin-funnel"><h1>Analytics query failed</h1><p>{error.message}</p></main>;
  const excludedIds=new Set((internalProfiles??[]).map(x=>x.user_id));
  const rows=((data??[]) as Row[]).filter(row=>q.include_internal==="1"||!row.user_id||!excludedIds.has(row.user_id));
  const groups=new Map<string,Row[]>();for(const row of rows){const list=groups.get(row.source)??[];list.push(row);groups.set(row.source,list);}
  const questions=new Map<number,{views:Set<string>;answers:Set<string>;errors:number;dwell:number[]}>();
  for(const row of rows){const number=Number(row.properties?.question_number);if(!number)continue;const item=questions.get(number)??{views:new Set(),answers:new Set(),errors:0,dwell:[]};if(row.event_name==="assessment_question_viewed")item.views.add(actor(row));if(row.event_name==="assessment_question_answered"){item.answers.add(actor(row));const dwell=Number(row.properties?.dwell_ms);if(Number.isFinite(dwell))item.dwell.push(dwell);}if(row.event_name==="assessment_validation_error")item.errors++;questions.set(number,item);}
  const bots=rows.filter(row=>row.bot_signal).length,latest=rows.slice(0,30);
  return <main className="admin-funnel"><p className="eyebrow">Internal acquisition diagnostics</p><h1>Funnel health</h1><p className="muted">Qualified session: a unique first-party session with at least one funnel event. Bot signals are shown for investigation and are not silently removed.</p>
    <form><label>Days<input name="days" type="number" min="1" max="365" defaultValue={days}/></label><label>Source<input name="source" defaultValue={q.source}/></label><label>Medium<input name="medium" defaultValue={q.medium}/></label><label>Campaign<input name="campaign" defaultValue={q.campaign}/></label><label>Device<select name="device" defaultValue={q.device}><option value="">All</option><option>mobile</option><option>desktop</option></select></label><label>Browser<input name="browser" defaultValue={q.browser}/></label><label>Variant<input name="variant" defaultValue={q.variant}/></label><label>Build<input name="version" defaultValue={q.version}/></label><label>Include staff/test<select name="include_internal" defaultValue={q.include_internal}><option value="0">No</option><option value="1">Yes</option></select></label><button className="button">Apply</button></form>
    <section className="admin-summary"><article><strong>{new Set(rows.map(actor)).size}</strong><span>qualified sessions</span></article><article><strong>{rows.length}</strong><span>events delivered</span></article><article><strong>{bots}</strong><span>bot-signal events</span></article><article><strong>{new Set(rows.map(r=>r.app_version).filter(Boolean)).size}</strong><span>build versions</span></article></section>
    <h2>Conversion by source</h2><div className="funnel-table"><table><thead><tr><th>Source</th>{labels.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{[...groups].sort((a,b)=>unique(b[1],stages[0])-unique(a[1],stages[0])).map(([source,sourceRows])=><tr key={source}><th>{source}</th>{stages.map((stage,index)=>{const seen=unique(sourceRows,stage),base=index===0?seen:unique(sourceRows,stages[index-1]);return <td key={stage}><strong>{seen}</strong>{index>0?<small>{base?Math.round(seen/base*100):0}% step · {unique(sourceRows,stages[0])?Math.round(seen/unique(sourceRows,stages[0])*100):0}% overall</small>:null}</td>})}</tr>)}</tbody></table></div>
    <h2>Assessment question health</h2><div className="funnel-table"><table><thead><tr><th>Question</th><th>Views</th><th>Answered</th><th>Continue rate</th><th>Validation errors</th><th>Median time</th></tr></thead><tbody>{[...questions].sort((a,b)=>a[0]-b[0]).map(([number,item])=><tr key={number}><th>Q{number}</th><td>{item.views.size}</td><td>{item.answers.size}</td><td>{item.views.size?Math.round(item.answers.size/item.views.size*100):0}%</td><td>{item.errors}</td><td>{median(item.dwell)/1000}s</td></tr>)}</tbody></table></div>
    <h2>Delivery debug</h2><div className="funnel-table"><table><thead><tr><th>Time</th><th>Event</th><th>Session</th><th>Route</th><th>Source / campaign</th><th>Device</th><th>Build</th></tr></thead><tbody>{latest.map(row=><tr key={row.id}><td>{new Date(row.created_at).toLocaleString()}</td><td>{row.event_name}</td><td>{actor(row).slice(0,12)}</td><td>{row.route??"—"}</td><td>{row.source} / {row.campaign??"—"}</td><td>{row.device} · {row.browser}{row.bot_signal?" · bot signal":""}</td><td>{row.app_version?.slice(0,10)??"legacy"}</td></tr>)}</tbody></table></div>
    <p className="muted">Staff/test accounts are excluded unless requested. Assessment answers and health free text are never stored in analytics.</p></main>;
}
