import { redirect } from "next/navigation";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { hasEditorialAccess } from "@/lib/editorial/access";

const stages = ["social_landing_view","assessment_start","assessment_complete","assessment_preview_view","signup_complete","checkout_start","subscription_complete"] as const;
const labels = ["Visitors","Starts","Completions","Previews","Accounts","Checkout","Paid"];
export default async function AcquisitionReport({searchParams}:{searchParams:Promise<{days?:string;source?:string;campaign?:string;device?:string;variant?:string}>}){
  const server=await createSupabaseServerClient(),{data:{user}}=server?await server.auth.getUser():{data:{user:null}};if(!await hasEditorialAccess(user))redirect("/app");
  const q=await searchParams,days=Math.min(365,Math.max(1,Number(q.days??30))),admin=createSupabaseAdminClient();let query=admin!.from("social_funnel_events").select("event_name,source,campaign,device,landing_variant,anonymous_session_id,user_id").gte("created_at",new Date(Date.now()-days*86400000).toISOString()).limit(50000);
  if(q.source)query=query.eq("source",q.source);if(q.campaign)query=query.eq("campaign",q.campaign);if(q.device)query=query.eq("device",q.device);if(q.variant)query=query.eq("landing_variant",q.variant);const[{data:events},{data:internalProfiles}]=await Promise.all([query,admin!.from("profiles").select("user_id").eq("is_internal",true)]),internalIds=new Set((internalProfiles??[]).map(x=>x.user_id)),customerEvents=(events??[]).filter(event=>!event.user_id||!internalIds.has(event.user_id));
  const grouped=new Map<string,typeof events>();for(const event of customerEvents){const list=grouped.get(event.source)??[];list.push(event);grouped.set(event.source,list)}
  return <main className="admin-funnel"><p className="eyebrow">Internal acquisition report</p><h1>Social funnel</h1><form><label>Days<input name="days" type="number" min="1" max="365" defaultValue={days}/></label><label>Source<input name="source" defaultValue={q.source}/></label><label>Campaign<input name="campaign" defaultValue={q.campaign}/></label><label>Device<select name="device" defaultValue={q.device}><option value="">All</option><option>mobile</option><option>desktop</option></select></label><label>Variant<input name="variant" defaultValue={q.variant}/></label><button className="button">Apply</button></form><div className="funnel-table"><table><thead><tr><th>Source</th>{labels.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{[...grouped].map(([source,rows])=><tr key={source}><th>{source}</th>{stages.map((stage,index)=>{const seen=new Set(rows!.filter(x=>x.event_name===stage).map(x=>x.user_id??x.anonymous_session_id??"event")).size,base=index===0?seen:new Set(rows!.filter(x=>x.event_name===stages[index-1]).map(x=>x.user_id??x.anonymous_session_id??"event")).size;return <td key={stage}><strong>{seen}</strong>{index>0?<small>{base?Math.round(seen/base*100):0}%</small>:null}</td>})}</tr>)}</tbody></table></div><p className="muted">Internal/test accounts are excluded from customer interpretation. This report stores funnel metadata only—never assessment answers or health free text.</p></main>
}
