import { createHash } from "node:crypto";
import { ImageResponse } from "next/og";
import { NextRequest, NextResponse } from "next/server";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { findArticle } from "@/modules/library/articles";
import { hasEditorialAccess } from "@/lib/editorial/access";
import { isSocialPlatform, isSocialTemplate, safeImageUrl, socialPlatforms } from "@/modules/social-studio/config";

export const runtime = "nodejs";
const orange = "#ff5a1f", ink = "#151613", ivory = "#f5f1e8";

function Brand() { return <div style={{display:"flex",alignItems:"center",gap:18,color:orange}}><svg width="54" height="54" viewBox="0 0 64 64"><path fill={orange} d="M12 8h43L43 20H24l-5 6h25l8 9-12 21H9l11-12h14l5-8H16L8 27z"/></svg><div style={{display:"flex",flexDirection:"column",fontWeight:900,letterSpacing:6,fontSize:22}}>STHENO<span style={{fontSize:9,letterSpacing:8}}>FITNESS</span></div></div>; }

function Artwork({ width, height, template, title, hook, subheadline, category, image, focalX, focalY, includeUrl }: { width:number;height:number;template:string;title:string;hook:string;subheadline:string;category:string;image:string|null;focalX:number;focalY:number;includeUrl:boolean }) {
  const portrait=height/width>1.3, pad=portrait?76:58, headline=portrait?70:Math.max(44,Math.min(72,width/17));
  const imagePanel=<div style={{display:"flex",width:"100%",height:"100%",backgroundImage:image?`linear-gradient(180deg,rgba(10,11,10,.05),rgba(10,11,10,.62)),url(${image})`:`radial-gradient(circle at ${focalX}% ${focalY}%,#ff7a45 0,#ff5a1f 18%,#2a211d 19%,#151613 58%,#080909 100%)`,backgroundSize:"cover",backgroundPosition:`${focalX}% ${focalY}%`}}/>;
  if(template==="bold-headline") return <div style={{display:"flex",width:"100%",height:"100%",padding:pad,background:ivory,color:ink,flexDirection:"column",justifyContent:"space-between"}}><Brand/><div style={{display:"flex",flexDirection:"column",borderLeft:`18px solid ${orange}`,paddingLeft:34}}><span style={{color:orange,fontSize:20,textTransform:"uppercase",letterSpacing:5}}>{category}</span><div style={{fontSize:headline+8,fontWeight:900,lineHeight:.92,letterSpacing:-3,marginTop:20}}>{hook||title}</div></div>{includeUrl?<div style={{fontSize:20,letterSpacing:3}}>STHENOFITNESS.COM</div>:<span/>}</div>;
  if(template==="key-takeaway") return <div style={{display:"flex",width:"100%",height:"100%",padding:pad,background:ink,color:ivory,flexDirection:"column",justifyContent:"space-between"}}><Brand/><div style={{display:"flex",flexDirection:"column"}}><span style={{color:orange,fontSize:19,textTransform:"uppercase",letterSpacing:5}}>KEY TAKEAWAY</span><div style={{fontSize:headline,fontWeight:700,lineHeight:1.05,marginTop:22}}>“{subheadline||hook}”</div></div><div style={{display:"flex",borderTop:"2px solid #ffffff33",paddingTop:24,fontSize:20}}>{title}</div></div>;
  if(template==="fitness-split"&&!portrait) return <div style={{display:"flex",width:"100%",height:"100%",background:ivory,color:ink}}><div style={{display:"flex",width:"48%",height:"100%"}}>{imagePanel}</div><div style={{display:"flex",width:"52%",padding:pad,flexDirection:"column",justifyContent:"space-between"}}><Brand/><div style={{display:"flex",flexDirection:"column"}}><span style={{color:orange,fontSize:18,textTransform:"uppercase",letterSpacing:4}}>{category}</span><div style={{fontSize:headline,fontWeight:900,lineHeight:.98,marginTop:18}}>{hook||title}</div></div>{includeUrl?<span style={{fontSize:18}}>STHENOFITNESS.COM</span>:<span/>}</div></div>;
  if(template==="story-cover") return <div style={{display:"flex",width:"100%",height:"100%",position:"relative",background:ink,color:ivory,overflow:"hidden"}}><div style={{display:"flex",position:"absolute",inset:0}}>{imagePanel}</div><div style={{display:"flex",position:"absolute",inset:0,padding:`${Math.max(110,pad)}px ${pad}px`,flexDirection:"column",justifyContent:"space-between"}}><Brand/><div style={{display:"flex",flexDirection:"column"}}><span style={{color:orange,fontSize:22,textTransform:"uppercase",letterSpacing:5}}>{category}</span><div style={{fontSize:headline+10,fontWeight:900,lineHeight:.94,marginTop:24}}>{hook||title}</div></div>{includeUrl?<div style={{fontSize:22,letterSpacing:4}}>READ AT STHENOFITNESS.COM</div>:<span/>}</div></div>;
  return <div style={{display:"flex",width:"100%",height:"100%",position:"relative",background:ink,color:ivory,overflow:"hidden"}}><div style={{display:"flex",position:"absolute",inset:0}}>{imagePanel}</div><div style={{display:"flex",position:"absolute",inset:0,padding:pad,flexDirection:"column",justifyContent:"space-between"}}><Brand/><div style={{display:"flex",flexDirection:"column",maxWidth:"92%"}}><span style={{color:orange,fontSize:19,textTransform:"uppercase",letterSpacing:5}}>{category}</span><div style={{fontSize:headline,fontWeight:900,lineHeight:.96,marginTop:18}}>{hook||title}</div><div style={{fontSize:Math.max(22,headline*.37),lineHeight:1.35,marginTop:24,color:"#e4dfd3"}}>{subheadline}</div></div>{includeUrl?<span style={{fontSize:19,letterSpacing:3}}>STHENOFITNESS.COM</span>:<span/>}</div></div>;
}

export async function GET(request: NextRequest, { params }: { params: Promise<{ slug: string }> }) {
  const { slug }=await params, article=findArticle(slug); if(!article)return NextResponse.json({error:"Article not found"},{status:404});
  if(request.nextUrl.searchParams.get("studio")==="1"){const db=await createSupabaseServerClient(),{data:{user}}=db?await db.auth.getUser():{data:{user:null}};if(!user||!await hasEditorialAccess(user))return NextResponse.json({error:"Unauthorized"},{status:401});}
  const p=request.nextUrl.searchParams,platform=isSocialPlatform(p.get("platform")??"")?p.get("platform")! as keyof typeof socialPlatforms:"x",template=isSocialTemplate(p.get("template")??"")?p.get("template")!:"editorial-hero",dimensions=socialPlatforms[platform];
  const headline=(p.get("headline")||article.title).slice(0,140),hook=(p.get("hook")||article.title).slice(0,140),subheadline=(p.get("subheadline")||article.thesis).slice(0,240),image=safeImageUrl(p.get("image")),focalX=Math.max(0,Math.min(100,Number(p.get("focalX")??50))),focalY=Math.max(0,Math.min(100,Number(p.get("focalY")??50))),includeUrl=p.get("includeUrl")!=="false";
  const config={slug,version:article.updatedAt,platform,template,headline,hook,subheadline,image,focalX,focalY,includeUrl},hash=createHash("sha256").update(JSON.stringify(config)).digest("hex"),storagePath=`articles/${slug}/${article.updatedAt}/${platform}/${template}-${hash.slice(0,16)}.png`,admin=createSupabaseAdminClient();
  if(admin){const{data}=await admin.from("social_assets").select("storage_path").eq("request_hash",hash).maybeSingle();if(data){const{data:publicUrl}=admin.storage.from("social-assets").getPublicUrl(data.storage_path);return NextResponse.redirect(publicUrl.publicUrl,307);}}
  const generated=new ImageResponse(<Artwork width={dimensions.width} height={dimensions.height} template={template} title={headline} hook={hook} subheadline={subheadline} category={article.pillar.replaceAll("-"," ")} image={image} focalX={focalX} focalY={focalY} includeUrl={includeUrl}/>,{width:dimensions.width,height:dimensions.height});
  const bytes=await generated.arrayBuffer();
  if(admin){const uploaded=await admin.storage.from("social-assets").upload(storagePath,bytes,{contentType:"image/png",upsert:true,cacheControl:"31536000"});if(!uploaded.error)await admin.from("social_assets").upsert({request_hash:hash,content_type:"article",content_id:slug,article_version:article.updatedAt,platform,template_id:template,configuration:config,storage_path:storagePath,width:dimensions.width,height:dimensions.height},{onConflict:"request_hash"});}
  return new NextResponse(bytes,{headers:{"Content-Type":"image/png","Cache-Control":"public, max-age=31536000, immutable","Content-Disposition":`inline; filename="${slug}-${platform}-${template}.png"`}});
}
