import { redirect } from "next/navigation";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { hasEditorialAccess } from "@/lib/editorial/access";

type Params={muscle?:string;equipment?:string;category?:string;movementType?:string;status?:string;issue?:string};
type Exercise={slug:string;name:string;primary_muscles:string[];required_equipment:string[];exercise_type:string;movement_type:string;prescription_unit:string;movement_pattern:string;purpose:string;education:Record<string,unknown>;technical_review_status:string;editorial_review_status:string;visual_review_status:string;production_ready:boolean;schema_valid:boolean;movement_type_valid:boolean;semantic_validation_passed:boolean;substitutions_validated:boolean;media_validated:boolean;quality_review_required:boolean};
const generic=new Set(["move with control through a comfortable range.","keep your breathing steady and your joints aligned.","stop the set before technique changes.","rushing the movement or using momentum.","forcing a range that causes pain.","losing the intended starting position."]);
function flags(x:Exercise){const issues:string[]=[];const e=x.education??{};if(!x.purpose||!x.movement_pattern||!x.primary_muscles?.length||!x.required_equipment?.length||!x.schema_valid)issues.push("missing fields");for(const field of ["setup","execution","cues","mistakes"]){const values=(e[field]??[]) as string[];if(values.length<2)issues.push("missing fields");if(values.some(v=>generic.has(v.toLowerCase())))issues.push("generic content");}if(!x.movement_type_valid)issues.push("movement type conflict");if(!x.semantic_validation_passed)issues.push("semantic flag");if(!x.substitutions_validated)issues.push("substitution review");if(!x.media_validated)issues.push("media review");if(x.technical_review_status!=="reviewed"||x.editorial_review_status!=="reviewed"||x.visual_review_status!=="reviewed"||!x.production_ready||x.quality_review_required)issues.push("review state");return [...new Set(issues)];}

export default async function ExerciseQuality({searchParams}:{searchParams:Promise<Params>}){
  const server=await createSupabaseServerClient(),{data:{user}}=server?await server.auth.getUser():{data:{user:null}};
  if(!await hasEditorialAccess(user))redirect("/app");
  const admin=createSupabaseAdminClient();if(!admin)return <main className="admin-funnel"><h1>Exercise QA unavailable</h1><p>The server database connection is not configured.</p></main>;
  const q=await searchParams,{data,error,count}=await admin.from("exercises").select("slug,name,primary_muscles,required_equipment,exercise_type,movement_type,prescription_unit,movement_pattern,purpose,education,technical_review_status,editorial_review_status,visual_review_status,production_ready,schema_valid,movement_type_valid,semantic_validation_passed,substitutions_validated,media_validated,quality_review_required",{count:"exact"}).eq("status","production").order("name").limit(1000);
  if(error)return <main className="admin-funnel"><h1>Exercise QA query failed</h1><p>{error.message}</p></main>;
  const all=(data??[]) as Exercise[],rows=all.map(x=>({x,issues:flags(x)})).filter(({x,issues})=>(!q.muscle||x.primary_muscles.includes(q.muscle))&&(!q.equipment||x.required_equipment.includes(q.equipment))&&(!q.category||x.exercise_type===q.category)&&(!q.movementType||x.movement_type===q.movementType)&&(!q.status||q.status==="reviewed"&&!issues.includes("review state")||q.status==="flagged"&&issues.length>0)&&(!q.issue||issues.includes(q.issue)));
  const reviewed=all.filter(x=>!flags(x).includes("review state")).length,flagged=all.filter(x=>flags(x).length).length,critical=all.filter(x=>flags(x).some(y=>y==="missing fields"||y==="review state")).length;
  return <main className="admin-funnel"><p className="eyebrow">Internal content integrity</p><h1>Exercise quality</h1><p className="muted">Live production records only. Filters affect the table; summary totals cover the entire production library.</p>
    <section className="admin-summary"><article><strong>{count??all.length}</strong><span>production exercises</span></article><article><strong>{reviewed}</strong><span>reviewed states</span></article><article><strong>{flagged}</strong><span>flagged records</span></article><article><strong>{critical}</strong><span>critical review flags</span></article></section>
    <form><label>Muscle<input name="muscle" defaultValue={q.muscle}/></label><label>Equipment<input name="equipment" defaultValue={q.equipment}/></label><label>Category<input name="category" defaultValue={q.category}/></label><label>Movement type<select name="movementType" defaultValue={q.movementType}><option value="">All</option>{[...new Set(all.map(x=>x.movement_type))].sort().map(value=><option key={value}>{value}</option>)}</select></label><label>Status<select name="status" defaultValue={q.status}><option value="">All</option><option value="reviewed">Reviewed</option><option value="flagged">Flagged</option></select></label><label>Issue<select name="issue" defaultValue={q.issue}><option value="">All</option>{["generic content","missing fields","movement type conflict","semantic flag","substitution review","media review","review state"].map(value=><option key={value}>{value}</option>)}</select></label><button className="button">Apply</button></form>
    <div className="funnel-table"><table><thead><tr><th>Exercise</th><th>Muscles</th><th>Equipment</th><th>Pattern</th><th>Prescription</th><th>Issues</th></tr></thead><tbody>{rows.map(({x,issues})=><tr key={x.slug}><th><a href={`/exercises/${x.slug}`}>{x.name}</a><small>{x.slug}</small></th><td>{x.primary_muscles.join(", ")}</td><td>{x.required_equipment.join(", ")}</td><td>{x.movement_pattern}</td><td>{x.movement_type}<small>{x.prescription_unit}</small></td><td>{issues.join(", ")||"—"}</td></tr>)}</tbody></table></div>
  </main>;
}
