import{NextResponse}from"next/server";import{z}from"zod";import{createSupabaseServerClient}from"@/lib/supabase/server";import{ASSESSMENT_VERSION,questions,validateAnswer,visibleQuestions}from"@/modules/assessment/definition";import{interpretFreeContext,INTERPRETER_VERSION}from"@/modules/assessment/interpret";import{buildPersonalizationProfile,PROFILE_VERSION,type AssessmentAnswers}from"@/modules/assessment/profile";import{screenSafety,SAFETY_SCREENING_VERSION}from"@/modules/assessment/safety";
const RequestSchema=z.discriminatedUnion("action",[
 z.object({action:z.literal("start")}),
 z.object({action:z.literal("restart")}),
 z.object({action:z.literal("save"),assessmentId:z.uuid(),questionKey:z.string(),value:z.union([z.string().max(5000),z.number(),z.array(z.string()).max(20)]),nextStepKey:z.string().nullable()}),
 z.object({action:z.literal("candidate"),assessmentId:z.uuid(),candidateId:z.uuid(),state:z.enum(["confirmed","edited","removed"]),value:z.string().max(1000).optional()}),
 z.object({action:z.literal("complete"),assessmentId:z.uuid()})
]);
async function context(){const supabase=await createSupabaseServerClient();if(!supabase)return null;const{data:{user}}=await supabase.auth.getUser();return user?{supabase,user}:null}
export async function GET(){const ctx=await context();if(!ctx)return NextResponse.json({error:"Unauthorized"},{status:401});const{data:assessment}=await ctx.supabase.from("assessments").select("id,status,current_step_key,started_at").eq("user_id",ctx.user.id).eq("status","started").order("started_at",{ascending:false}).limit(1).maybeSingle();if(!assessment)return NextResponse.json({assessment:null,answers:{},candidates:[]});const[{data:responses},{data:candidates}]=await Promise.all([ctx.supabase.from("assessment_responses").select("question_key,response_value").eq("assessment_id",assessment.id).eq("user_id",ctx.user.id),ctx.supabase.from("interpreted_context_candidates").select("id,candidate_type,normalized_value,confidence,temporal_scope,safety_flag,confirmation_state").eq("assessment_id",assessment.id).eq("user_id",ctx.user.id).neq("confirmation_state","removed")]);return NextResponse.json({assessment,answers:Object.fromEntries((responses??[]).map(r=>[r.question_key,r.response_value])),candidates:candidates??[]})}
export async function POST(request:Request){const ctx=await context();if(!ctx)return NextResponse.json({error:"Unauthorized"},{status:401});const parsed=RequestSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Invalid assessment request"},{status:400});const body=parsed.data;
 if(body.action==="start"||body.action==="restart"){const{data:version}=await ctx.supabase.from("assessment_versions").select("id").eq("version",ASSESSMENT_VERSION).eq("status","active").single();if(!version)return NextResponse.json({error:"Assessment version unavailable"},{status:503});const{data:existing}=await ctx.supabase.from("assessments").select("id").eq("user_id",ctx.user.id).eq("status","started").order("started_at",{ascending:false}).limit(1).maybeSingle();if(existing&&body.action==="start")return NextResponse.json({assessmentId:existing.id});if(existing){const{error:abandonError}=await ctx.supabase.from("assessments").update({status:"abandoned",updated_at:new Date().toISOString()}).eq("id",existing.id).eq("user_id",ctx.user.id);if(abandonError)return NextResponse.json({error:"Unable to restart assessment"},{status:500})}const{data,error}=await ctx.supabase.from("assessments").insert({user_id:ctx.user.id,assessment_version_id:version.id,status:"started",current_step_key:questions[0].key,derivation_version:PROFILE_VERSION}).select("id").single();if(error)return NextResponse.json({error:error.message},{status:400});await ctx.supabase.from("profiles").update({lifecycle_state:"assessment_started",updated_at:new Date().toISOString()}).eq("user_id",ctx.user.id);return NextResponse.json({assessmentId:data.id});}
 if(body.action==="save"){const question=questions.find(q=>q.key===body.questionKey);if(!question)return NextResponse.json({error:"Unknown question"},{status:400});const validationError=validateAnswer(question,body.value);if(validationError)return NextResponse.json({error:validationError},{status:400});const now=new Date().toISOString();const{data:response,error}=await ctx.supabase.from("assessment_responses").upsert({user_id:ctx.user.id,assessment_id:body.assessmentId,question_key:body.questionKey,response_value:body.value,question_version:"1",answered_at:now,updated_at:now},{onConflict:"assessment_id,question_key"}).select("id").single();if(error)return NextResponse.json({error:error.message},{status:400});await Promise.all([ctx.supabase.from("assessment_response_revisions").insert({user_id:ctx.user.id,assessment_id:body.assessmentId,question_key:body.questionKey,response_value:body.value,question_version:"1",recorded_at:now}),ctx.supabase.from("assessments").update({current_step_key:body.nextStepKey,updated_at:now}).eq("id",body.assessmentId).eq("user_id",ctx.user.id)]);
  if(["pain_context","movement_limits","free_context"].includes(body.questionKey)&&typeof body.value==="string"&&body.value.trim()){const safety=screenSafety(body.value);let sourceEntryId:null|string=null;if(body.questionKey==="free_context"){const{data:entry}=await ctx.supabase.from("assessment_context_entries").insert({user_id:ctx.user.id,assessment_id:body.assessmentId,entry_type:"free_form",content:body.value.trim()}).select("id").single();sourceEntryId=entry?.id??null;if(sourceEntryId){await ctx.supabase.from("interpreted_context_candidates").update({confirmation_state:"removed",decided_at:now}).eq("assessment_id",body.assessmentId).eq("user_id",ctx.user.id).eq("confirmation_state","pending");const candidates=interpretFreeContext(body.value).map(c=>({user_id:ctx.user.id,assessment_id:body.assessmentId,source_entry_id:sourceEntryId,candidate_type:c.type,normalized_value:c.value,confidence:c.confidence,temporal_scope:c.temporalScope,safety_flag:c.safetyFlag,confirmation_required:c.confirmationRequired,interpreter_version:INTERPRETER_VERSION}));if(candidates.length)await ctx.supabase.from("interpreted_context_candidates").insert(candidates);}}
   await ctx.supabase.from("safety_screening_results").insert({user_id:ctx.user.id,assessment_id:body.assessmentId,source_response_id:response.id,source_context_entry_id:sourceEntryId,classification:safety.classification,reason_codes:safety.reasonCodes,screening_version:SAFETY_SCREENING_VERSION});}
  return NextResponse.json({saved:true});}
 if(body.action==="candidate"){const value=body.state==="edited"?{summary:body.value??""}:undefined;const{error}=await ctx.supabase.from("interpreted_context_candidates").update({confirmation_state:body.state,confirmed_value:value,decided_at:new Date().toISOString()}).eq("id",body.candidateId).eq("assessment_id",body.assessmentId).eq("user_id",ctx.user.id);return error?NextResponse.json({error:error.message},{status:400}):NextResponse.json({saved:true});}
 const{data:responses}=await ctx.supabase.from("assessment_responses").select("question_key,response_value").eq("assessment_id",body.assessmentId).eq("user_id",ctx.user.id);const answers=Object.fromEntries((responses??[]).map(r=>[r.question_key,r.response_value]))as AssessmentAnswers;const missing=visibleQuestions(answers).filter(q=>{const answer=answers[q.key];return q.required&&(answer===undefined||answer===""||(Array.isArray(answer)&&answer.length===0))});if(missing.length)return NextResponse.json({error:`Complete: ${missing[0].prompt}`,questionKey:missing[0].key},{status:400});const built=buildPersonalizationProfile(answers);const{error}=await ctx.supabase.from("personalization_profile_snapshots").insert({user_id:ctx.user.id,assessment_id:body.assessmentId,profile_version:PROFILE_VERSION,profile:built.profile,provenance:built.provenance,safety_classification:built.safety.classification});if(error)return NextResponse.json({error:error.message},{status:400});await Promise.all([ctx.supabase.from("assessments").update({status:"completed",completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",body.assessmentId).eq("user_id",ctx.user.id),ctx.supabase.from("profiles").update({lifecycle_state:"assessment_completed",updated_at:new Date().toISOString()}).eq("user_id",ctx.user.id)]);return NextResponse.json({completed:true,safety:built.safety.classification});}
