import { writeFile } from "node:fs/promises";

const origin=process.argv[2]??"https://www.sthenofitness.com";
const strip=s=>s?.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&[^;]+;/g," ").replace(/\s+/g," ").trim()??"";
const attr=(html,name,property=false)=>{const key=property?"property":"name";const re=new RegExp(`<meta[^>]+${key}=["']${name}["'][^>]+content=["']([^"']*)["']|<meta[^>]+content=["']([^"']*)["'][^>]+${key}=["']${name}["']`,"i"),m=html.match(re);return m?.[1]??m?.[2]??""};
const tag=(html,name)=>strip(html.match(new RegExp(`<${name}[^>]*>([\\s\\S]*?)<\\/${name}>`,"i"))?.[1]);
const link=(html,rel)=>html.match(new RegExp(`<link[^>]+rel=["']${rel}["'][^>]+href=["']([^"']+)["']|<link[^>]+href=["']([^"']+)["'][^>]+rel=["']${rel}["']`,"i"))?.slice(1).find(Boolean)??"";
const xml=await (await fetch(`${origin}/sitemap.xml`)).text();
const urls=[...xml.matchAll(/<loc>(.*?)<\/loc>/g)].map(m=>m[1]);
const robots=await (await fetch(`${origin}/robots.txt`)).text();
const rows=[];
for(let i=0;i<urls.length;i+=8){await Promise.all(urls.slice(i,i+8).map(async url=>{try{const response=await fetch(url,{redirect:"follow"}),html=await response.text(),canonical=link(html,"canonical"),title=tag(html,"title"),description=attr(html,"description"),h1=tag(html,"h1"),body=strip(html),jsonld=[...html.matchAll(/<script[^>]+application\/ld\+json[^>]*>([\s\S]*?)<\/script>/gi)].flatMap(m=>{try{const j=JSON.parse(m[1]);return [j["@type"]??j?.["@graph"]?.map(x=>x["@type"]).filter(Boolean).join("|")].filter(Boolean)}catch{return[]}}),links=[...html.matchAll(/<a[^>]+href=["']([^"'#]+)["']/gi)].map(m=>m[1]),images=[...html.matchAll(/<img[^>]+(?:src=["']([^"']+)["'][^>]*alt=["']([^"']*)["']|alt=["']([^"']*)["'][^>]*src=["']([^"']+)["'])/gi)];rows.push({url,pageType:new URL(url).pathname.split("/")[1]||"homepage",status:response.status,canonical,indexState:/noindex/i.test(attr(html,"robots"))?"noindex":"index",robotsAccessible:!robots.split(/\r?\n/).some(line=>line.toLowerCase().startsWith("disallow:")&&new URL(url).pathname.startsWith(line.split(":")[1].trim())),sitemap:true,title,titleLength:title.length,description,descriptionLength:description.length,h1,published:attr(html,"article:published_time",true),modified:attr(html,"article:modified_time",true),ogTitle:attr(html,"og:title",true),ogDescription:attr(html,"og:description",true),ogImage:attr(html,"og:image",true),twitterCard:attr(html,"twitter:card"),structuredData:jsonld.join("|"),author:attr(html,"author"),wordCount:body.split(/\s+/).filter(Boolean).length,primaryImage:images[0]?.[1]??images[0]?.[4]??"",primaryImageAlt:images[0]?.[2]??images[0]?.[3]??"",internalLinks:links.filter(h=>h.startsWith("/")||h.startsWith(origin)).length,externalLinks:links.filter(h=>/^https?:/.test(h)&&!h.startsWith(origin)).length,canonicalConflict:canonical&&canonical!==url?canonical:""})}catch(error){rows.push({url,status:0,error:String(error)})}}))}
rows.sort((a,b)=>a.url.localeCompare(b.url));
const columns=[...new Set(rows.flatMap(Object.keys))],quote=v=>`"${String(v??"").replaceAll('"','""')}"`;
await writeFile("docs/seo-url-inventory.csv",[columns.map(quote).join(","),...rows.map(row=>columns.map(c=>quote(row[c])).join(","))].join("\n"));
const duplicate=(key)=>Object.entries(Object.groupBy(rows.filter(r=>r[key]),r=>r[key])).filter(([,group])=>group.length>1).map(([value,group])=>`- ${key}: “${value}” — ${group.length} URLs`).join("\n")||"- None detected.";
const summary=`# Production SEO audit\n\nGenerated ${new Date().toISOString()} against ${origin}. The CSV inventory is the source of truth for per-URL fields.\n\n## Coverage\n\n- Sitemap URLs audited: ${rows.length}\n- Non-200 responses: ${rows.filter(r=>r.status!==200).length}\n- Missing canonical: ${rows.filter(r=>!r.canonical).length}\n- Missing description: ${rows.filter(r=>!r.description).length}\n- Missing H1: ${rows.filter(r=>!r.h1).length}\n- Canonical conflicts: ${rows.filter(r=>r.canonicalConflict).length}\n- Pages with structured data: ${rows.filter(r=>r.structuredData).length}\n\n## Duplicate titles\n\n${duplicate("title")}\n\n## Duplicate descriptions\n\n${duplicate("description")}\n\n## Index strategy\n\nPublic canonical marketing, article, tool, comparison, library, and reviewed exercise URLs are indexed and included in the sitemap. Auth, account, API, app, diagnostics, and campaign duplicate routes are excluded or noindexed.\n\n## Interpretation\n\nCharacter counts are diagnostic, not targets. Thin or repetitive pages require editorial judgment; they are not padded automatically. Meaningful content dates, rather than deployment dates, drive article and exercise lastmod values.\n`;
await writeFile("docs/seo-audit.md",summary);
console.log(`Audited ${rows.length} URLs.`);
