import type{BlueprintInput}from"./blueprint";
export const ASSESSMENT_VERSION="3.0.0";
export type Intake=Partial<BlueprintInput>&Record<string,string|number|string[]|undefined>;
export type IntakeStep={key:string;section:string;question:string;help:string;type:"single"|"multi"|"number"|"text";options?:{value:string;label:string;detail?:string}[];optional?:boolean;min?:number;max?:number;unit?:string;show?:(a:Intake)=>boolean};
const options=(...rows:[string,string,string?][])=>rows.map(([value,label,detail])=>({value,label,detail}));
export const intakeSteps:IntakeStep[]=[
{key:"goal",section:"Your direction",question:"What should your plan accomplish first?",help:"Pick the result that matters most. This becomes the plan’s primary decision filter.",type:"single",options:options(["strength","Build strength"],["muscle","Build muscle"],["fat_loss","Lose fat sustainably"],["general","Feel fitter and more capable"])},
{key:"secondaryGoal",section:"Your direction",question:"What should the plan support alongside that?",help:"Choose a second priority so the plan does not solve one goal by ignoring another.",type:"single",optional:true,options:options(["energy","More energy"],["mobility","Move comfortably"],["confidence","Gym confidence"],["cardio","Cardio fitness"],["none","No secondary goal"])},
{key:"specificOutcome",section:"Your direction",question:"What would meaningful progress look like?",help:"For example: complete five full push-ups, lose 15 lb, or train three days consistently.",type:"text"},
{key:"timeframe",section:"Your direction",question:"Is there a timeframe or event?",help:"A date shapes pacing, but it never overrides safe progression.",type:"single",optional:true,options:options(["none","No fixed deadline"],["8-12","8–12 weeks"],["3-6","3–6 months"],["event","A specific event"])},
{key:"priorityStyle",section:"Your direction",question:"Which result feels most important?",help:"This helps settle tradeoffs when several goals compete.",type:"single",options:options(["appearance","Appearance"],["strength","Strength"],["fitness","Everyday fitness"],["performance","Sport or performance"])},
{key:"age",section:"Starting profile",question:"How old are you?",help:"Age informs recovery assumptions without defining your ability.",type:"number",min:16,max:90,unit:"years"},
{key:"sex",section:"Starting profile",question:"Which input should nutrition equations use?",help:"Some population equations include sex. Prefer not to say uses a broader estimate.",type:"single",optional:true,options:options(["female","Female"],["male","Male"],["prefer_not","Prefer not to say"])},
{key:"heightFeet",section:"Starting profile",question:"What is your height in feet?",help:"The next screen asks for the remaining inches.",type:"number",min:3,max:7,unit:"ft"},
{key:"heightInches",section:"Starting profile",question:"And the remaining inches?",help:"Use 0 if your height is an exact number of feet.",type:"number",min:0,max:11,unit:"in"},
{key:"weightLb",section:"Starting profile",question:"What is your current body weight?",help:"An approximate value is enough. This is context, not a score.",type:"number",min:75,max:550,unit:"lb"},
{key:"waistInches",section:"Starting profile",question:"Would you like to include waist context?",help:"Optional. Use inches and measure consistently if you plan to track it.",type:"number",optional:true,min:20,max:80,unit:"in",show:a=>a.goal==="fat_loss"||a.goal==="muscle"},
{key:"experience",section:"Training history",question:"How much structured strength training have you done?",help:"This changes exercise complexity, starting volume, and explanation.",type:"single",options:options(["new","New to it"],["returning","Returning after time away"],["consistent","Consistent for a year or more"])},
{key:"consistencyHistory",section:"Training history",question:"What has consistency looked like over the last year?",help:"Choose the closest honest description—not your best month.",type:"single",options:options(["none","Almost none"],["intermittent","Starts and stops"],["seasonal","Consistent in stretches"],["steady","Mostly steady"])},
{key:"currentFrequency",section:"Training history",question:"How often are you training now?",help:"Include strength, classes, or sport that meaningfully affects recovery.",type:"single",options:options(["0","Not currently"],["1-2","1–2 days"],["3-4","3–4 days"],["5+","5+ days"])},
{key:"previousApproaches",section:"Training history",question:"What approaches have you tried?",help:"Select the formats you know enough to have an opinion about.",type:"multi",optional:true,show:a=>a.experience==="returning"||a.experience==="consistent",options:options(["gym","Gym programs"],["classes","Group classes"],["apps","Fitness apps"],["trainer","Personal trainer"],["home","Home workouts"],["sport","Sports or endurance"])},
{key:"workedBefore",section:"Training history",question:"What worked—or did not work—before?",help:"A few sentences can prevent us from repeating a plan you already know fails.",type:"text",optional:true,show:a=>a.experience==="returning"||a.experience==="consistent"},
{key:"days",section:"Your week",question:"How many training days can you realistically protect?",help:"Choose a normal week, not a perfect week.",type:"single",options:options(["2","2 days"],["3","3 days"],["4","4 days"],["5","5 days"])},
{key:"duration",section:"Your week",question:"How long can a normal session take?",help:"Include warm-up, equipment setup, and transitions.",type:"single",options:options(["30","30 minutes"],["45","45 minutes"],["60","60 minutes"],["75","75 minutes"])},
{key:"preferredDays",section:"Your week",question:"Which days usually work best?",help:"Select every realistic training window.",type:"multi",options:options(["mon","Monday"],["tue","Tuesday"],["wed","Wednesday"],["thu","Thursday"],["fri","Friday"],["sat","Saturday"],["sun","Sunday"])},
{key:"schedule",section:"Your week",question:"How predictable is your schedule?",help:"Variable weeks need backup sessions, not guilt.",type:"single",options:options(["stable","Mostly stable"],["variable","Changes week to week"],["shifts","Shift or rotating work"],["caregiving","Family or caregiving changes it"])},
{key:"travel",section:"Your week",question:"Any travel or disruption coming up?",help:"We can prepare shorter or equipment-flexible sessions before you need them.",type:"single",optional:true,show:a=>a.schedule!=="stable",options:options(["none","Nothing planned"],["soon","Something soon"],["occasional","Occasional travel"],["frequent","Frequent travel"])},
{key:"location",section:"Training environment",question:"Where will you train most often?",help:"The plan should fit the environment you actually use.",type:"single",options:options(["gym","Commercial gym"],["home","Home gym"],["mixed","Home and gym"],["hotel","Travel or hotel gyms"])},
{key:"equipment",section:"Training environment",question:"What equipment is reliably available?",help:"Select only what you can use most weeks.",type:"multi",options:options(["dumbbells","Dumbbells"],["barbell","Barbell + rack"],["bench","Bench"],["cables","Cables"],["machines","Machines"],["bands","Bands"],["cardio","Cardio equipment"],["bodyweight","Bodyweight only"])},
{key:"dumbbellLimitLb",section:"Training environment",question:"What is your heaviest dumbbell?",help:"This helps progression stay realistic at home. Skip if it does not apply.",type:"number",optional:true,min:1,max:200,unit:"lb each",show:a=>Array.isArray(a.equipment)&&a.equipment.includes("dumbbells")&&(a.location==="home"||a.location==="mixed")},
{key:"familiarity",section:"Training preferences",question:"How comfortable are you setting up exercises?",help:"We will trade complexity for clarity when useful.",type:"single",options:options(["low","I want detailed guidance"],["some","I know common movements"],["high","I am comfortable with most equipment"])},
{key:"preferences",section:"Training preferences",question:"What training or exercises do you enjoy?",help:"Enjoyment is useful program data, not a bonus.",type:"text",optional:true},
{key:"dislikes",section:"Training preferences",question:"Anything you strongly dislike or want to avoid?",help:"We can usually preserve the training purpose with a different exercise or style.",type:"text",optional:true,show:a=>a.experience!=="new"},
{key:"limitations",section:"Safety and comfort",question:"Any discomfort, limitations, or interruptions to accommodate?",help:"Describe movements or situations—not a self-diagnosis. Concerning symptoms need qualified care.",type:"text",optional:true},
{key:"activity",section:"Activity and recovery",question:"How active is the rest of your day?",help:"Consider work, walking, commuting, and caregiving.",type:"single",options:options(["low","Mostly seated"],["moderate","A mix of sitting and moving"],["high","On my feet most of the day"])},
{key:"steps",section:"Activity and recovery",question:"About how many steps do you average?",help:"Optional. A rough phone or watch estimate is enough.",type:"single",optional:true,show:a=>a.activity!=="high",options:options(["under4k","Under 4,000"],["4-7k","4,000–7,000"],["7-10k","7,000–10,000"],["10k+","More than 10,000"],["unknown","I do not know"])},
{key:"sleepHours",section:"Activity and recovery",question:"How many hours do you usually sleep?",help:"Use the typical amount, not time spent in bed.",type:"number",min:3,max:12,unit:"hours"},
{key:"sleep",section:"Activity and recovery",question:"How restorative does sleep feel?",help:"Quantity and quality can tell different stories.",type:"single",options:options(["poor","Frequently difficult"],["mixed","Inconsistent"],["good","Usually restorative"])},
{key:"stress",section:"Activity and recovery",question:"How demanding does life feel right now?",help:"We use this to set a recoverable starting dose—not to judge resilience.",type:"single",show:a=>a.sleep!=="good",options:options(["low","Manageable"],["moderate","Busy but workable"],["high","Very demanding"])},
{key:"diet",section:"Nutrition",question:"Which eating pattern should guidance fit?",help:"The plan should work with your food preferences and culture.",type:"single",options:options(["flexible","No specific pattern"],["omnivore","Omnivore"],["vegetarian","Vegetarian"],["vegan","Vegan"])},
{key:"meals",section:"Nutrition",question:"How many meals do you normally eat?",help:"We will distribute nutrition across the pattern you already use.",type:"single",show:a=>a.goal==="fat_loss"||a.goal==="muscle",options:options(["2","2 meals"],["3","3 meals"],["4","4+ meals or snacks"],["variable","It varies"])},
{key:"tracking",section:"Nutrition",question:"How much tracking are you willing to do?",help:"Tracking is optional. The lowest-friction method that improves decisions is usually best.",type:"single",show:a=>a.goal==="fat_loss"||a.goal==="muscle",options:options(["none","No calorie tracking"],["portions","Simple portions"],["short","Short learning period"],["full","Detailed tracking is fine"])},
{key:"proteinContext",section:"Nutrition",question:"How consistently do you include protein?",help:"Think across normal meals rather than exceptional days.",type:"single",show:a=>a.goal==="fat_loss"||a.goal==="muscle",options:options(["rare","Once a day or less"],["some","At one or two meals"],["most","At most meals"],["unknown","Not sure"])},
{key:"nutritionBarriers",section:"Nutrition",question:"What makes eating for your goal difficult?",help:"Examples include time, cost, appetite, cooking, family meals, alcohol, or hydration.",type:"text",optional:true,show:a=>a.goal==="fat_loss"||a.goal==="muscle"},
{key:"supplements",section:"Supplements",question:"Which fitness supplements do you currently use?",help:"Select any that apply. We will keep guidance evidence-led and conservative.",type:"multi",optional:true,options:options(["none","None"],["protein","Protein powder"],["creatine","Creatine"],["caffeine","Pre-workout or caffeine"],["vitamins","Vitamins or minerals"],["other","Other"])},
{key:"supplementGuidance",section:"Supplements",question:"Would evidence-based supplement guidance help?",help:"We will separate likely benefit, dose, risk, testing, and cost.",type:"single",options:options(["yes","Yes"],["maybe","Only when relevant"],["no","No thanks"])},
{key:"barriers",section:"Making it stick",question:"What is the biggest obstacle right now?",help:"The plan should be built around the obstacle, not surprised by it.",type:"single",options:options(["time","Time"],["consistency","Consistency"],["confidence","Confidence"],["energy","Energy"],["pain","Discomfort or limitations"],["direction","Not knowing what to do"])},
{key:"stoppingReasons",section:"Making it stick",question:"Why have previous plans stopped?",help:"Be direct. This answer often matters more than another exercise choice.",type:"text",optional:true,show:a=>a.consistencyHistory==="intermittent"||a.consistencyHistory==="seasonal"},
{key:"supportStyle",section:"Making it stick",question:"What kind of support helps you follow through?",help:"Choose the coaching style you are most likely to use.",type:"single",options:options(["clear","Clear instructions"],["flexible","Flexible backup options"],["accountability","Check-ins and accountability"],["explanation","Understanding why"])},
{key:"context",section:"Final context",question:"Anything else you want your coach to know?",help:"Share schedule details, equipment, exercises, travel, concerns, previous experience, or preferences we missed.",type:"text",optional:true}
];
export function visibleSteps(answers:Intake){return intakeSteps.filter(step=>!step.show||step.show(answers))}
export function reviewGroups(answers:Intake){return [...new Set(visibleSteps(answers).map(x=>x.section))].map(section=>({section,items:visibleSteps(answers).filter(x=>x.section===section&&answers[x.key]!==undefined&&answers[x.key]!=="")}))}
