export type AssessmentOption={value:string;label:string};
export type AssessmentQuestion={key:string;section:string;prompt:string;help?:string;type:"single"|"multi"|"number"|"text";required:boolean;options?:AssessmentOption[];min?:number;max?:number;unit?:string;showWhen?:{key:string;includes:string}};

export const ASSESSMENT_VERSION="initial-v1";
export const questions:AssessmentQuestion[]=[
 {key:"primary_goal",section:"Goal",prompt:"What would you most like STHENO to help you accomplish?",type:"single",required:true,options:[{value:"build_strength",label:"Build strength"},{value:"build_muscle",label:"Build muscle"},{value:"lose_fat",label:"Lose body fat"},{value:"general_fitness",label:"Improve general fitness"},{value:"endurance",label:"Improve endurance"}]},
 {key:"secondary_goals",section:"Goal",prompt:"Anything else you want to improve?",type:"multi",required:false,options:[{value:"strength",label:"Strength"},{value:"muscle",label:"Muscle"},{value:"body_composition",label:"Body composition"},{value:"mobility",label:"Mobility"},{value:"energy",label:"Energy"}]},
 {key:"experience",section:"Training",prompt:"What best describes your resistance-training experience?",type:"single",required:true,options:[{value:"new",label:"New to resistance training"},{value:"beginner",label:"Less than 1 year"},{value:"intermediate",label:"1–3 consistent years"},{value:"advanced",label:"More than 3 consistent years"}]},
 {key:"recent_consistency",section:"Training",prompt:"How consistently have you trained over the last 3 months?",type:"single",required:true,options:[{value:"none",label:"Not at all"},{value:"inconsistent",label:"On and off"},{value:"most_weeks",label:"Most weeks"},{value:"very_consistent",label:"Very consistently"}]},
 {key:"days_per_week",section:"Schedule",prompt:"How many days per week can you realistically train?",help:"Choose the schedule you can repeat, not the perfect week.",type:"number",required:true,min:1,max:7,unit:"days"},
 {key:"preferred_days",section:"Schedule",prompt:"Which days usually work best?",type:"multi",required:false,options:["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday","Flexible"].map(label=>({value:label.toLowerCase(),label}))},
 {key:"session_minutes",section:"Schedule",prompt:"How much time can you give most workouts?",type:"single",required:true,options:[{value:"30",label:"30 minutes"},{value:"45",label:"45 minutes"},{value:"60",label:"60 minutes"},{value:"75",label:"75 minutes"},{value:"90",label:"90+ minutes"}]},
 {key:"environment",section:"Equipment",prompt:"Where will you usually train?",type:"single",required:true,options:[{value:"gym",label:"Gym"},{value:"home",label:"Home"},{value:"both",label:"Both"},{value:"other",label:"Somewhere else"}]},
 {key:"equipment",section:"Equipment",prompt:"What equipment do you reliably have access to?",type:"multi",required:true,options:[{value:"barbell",label:"Barbell and plates"},{value:"dumbbells",label:"Dumbbells"},{value:"machines",label:"Resistance machines"},{value:"cables",label:"Cable station"},{value:"bench",label:"Bench"},{value:"bands",label:"Resistance bands"},{value:"bodyweight",label:"Bodyweight only"}]},
 {key:"enjoy",section:"Preferences",prompt:"What types of training do you especially enjoy?",type:"text",required:false},
 {key:"dislike",section:"Preferences",prompt:"Anything you strongly dislike or prefer not to do?",type:"text",required:false},
 {key:"movement_limits",section:"Safety",prompt:"Any movements you cannot perform or have been told not to perform?",help:"Report what you know. STHENO will not diagnose the cause.",type:"text",required:false},
 {key:"pain_context",section:"Safety",prompt:"Any current pain or discomfort that could affect exercise?",help:"Severe or sudden symptoms need appropriate medical attention, not an app assessment.",type:"text",required:false},
 {key:"height",section:"Baseline",prompt:"What is your height?",type:"number",required:true,min:36,max:96,unit:"inches"},
 {key:"weight",section:"Baseline",prompt:"What is your current body weight?",type:"number",required:true,min:70,max:700,unit:"lb"},
 {key:"activity",section:"Lifestyle",prompt:"What best describes your typical daily activity?",type:"single",required:true,options:[{value:"low",label:"Mostly seated"},{value:"light",label:"Some walking"},{value:"moderate",label:"Regularly active"},{value:"high",label:"Highly active or physical job"}]},
 {key:"sleep",section:"Lifestyle",prompt:"How much do you usually sleep?",type:"single",required:true,options:[{value:"under_6",label:"Under 6 hours"},{value:"6_7",label:"6–7 hours"},{value:"7_8",label:"7–8 hours"},{value:"over_8",label:"More than 8 hours"}]},
 {key:"cardio",section:"Cardio",prompt:"What cardio or endurance activity do you currently do?",type:"text",required:false},
 {key:"diet",section:"Nutrition context",prompt:"Any dietary preferences or restrictions relevant to future guidance?",type:"text",required:false},
 {key:"tracking_comfort",section:"Nutrition context",prompt:"How comfortable are you tracking calories or macros?",type:"single",required:true,options:[{value:"not_interested",label:"I prefer not to track"},{value:"open",label:"Open to it"},{value:"comfortable",label:"Comfortable tracking"},{value:"experienced",label:"Experienced tracker"}]},
 {key:"timeframe",section:"Goal",prompt:"Do you have a goal timeframe?",help:"A date gives context; it is not a promise of a specific outcome.",type:"text",required:false},
 {key:"free_context",section:"Final context",prompt:"Anything else we should know?",help:"Tell STHENO about your schedule, exercises you love or hate, equipment limitations, previous training, upcoming travel, or anything else we did not ask.",type:"text",required:false},
];

export function visibleQuestions(answers:Record<string,unknown>){return questions.filter(q=>{if(!q.showWhen)return true;const answer=answers[q.showWhen.key];return Array.isArray(answer)&&answer.includes(q.showWhen.includes)});}
export function validateAnswer(question:AssessmentQuestion,value:unknown){if(question.required&&(value===""||value===undefined||(Array.isArray(value)&&value.length===0)))return"Answer required";if(question.type==="number"){if(typeof value!=="number"||!Number.isFinite(value))return"Enter a valid number";if(question.min!==undefined&&value<question.min)return`Enter ${question.min} or more`;if(question.max!==undefined&&value>question.max)return`Enter ${question.max} or less`;}if(question.type==="single"&&value!==""&&!question.options?.some(option=>option.value===value))return"Choose a valid option";if(question.type==="multi"&&(!Array.isArray(value)||value.some(item=>!question.options?.some(option=>option.value===item))))return"Choose valid options";return null}
