create extension if not exists pgcrypto;
create type public.lifecycle_state as enum ('visitor','assessment_started','assessment_completed','account_created','trial','active','past_due','cancelled','expired');
create type public.safety_classification as enum ('normal','caution','modify','stop','refer');

create table public.profiles (user_id uuid primary key references auth.users(id) on delete cascade, display_name text, lifecycle_state public.lifecycle_state not null default 'account_created', time_zone text not null default 'UTC', deletion_requested_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.user_preferences (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, unit_system text not null default 'imperial' check(unit_system in('imperial','metric')), locale text not null default 'en-US', created_at timestamptz not null default now());
create unique index user_preferences_owner_key on public.user_preferences(user_id);
create table public.consents (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, consent_type text not null, version text not null, granted boolean not null, recorded_at timestamptz not null default now());
create index consents_owner_time_idx on public.consents(user_id,recorded_at desc);
create table public.subscriptions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, stripe_customer_id text, stripe_subscription_id text unique, status text not null, billing_interval text check(billing_interval in('month','year')), trial_ends_at timestamptz, current_period_ends_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index subscriptions_owner_idx on public.subscriptions(user_id);
create table public.subscription_events (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, subscription_id uuid references public.subscriptions(id) on delete set null, provider_event_id text unique, event_type text not null, occurred_at timestamptz not null, created_at timestamptz not null default now());
create table public.entitlements (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, entitlement_key text not null, active boolean not null default true, starts_at timestamptz not null default now(), ends_at timestamptz, source_subscription_id uuid references public.subscriptions(id) on delete set null, created_at timestamptz not null default now());
create index entitlements_owner_active_idx on public.entitlements(user_id,active);

create table public.fitness_profiles (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, experience_level text, available_days smallint check(available_days between 1 and 7), session_minutes smallint check(session_minutes between 10 and 240), effective_from timestamptz not null default now(), effective_to timestamptz, created_at timestamptz not null default now());
create index fitness_profiles_owner_history_idx on public.fitness_profiles(user_id,effective_from desc);
create table public.goals (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, goal_type text not null, target_value numeric, target_unit text, starts_at date not null, ends_at date, supersedes_goal_id uuid references public.goals(id), created_at timestamptz not null default now());
create index goals_owner_history_idx on public.goals(user_id,starts_at desc);
create table public.assessment_versions (id uuid primary key default gen_random_uuid(), version text not null unique, status text not null check(status in('draft','active','retired')), published_at timestamptz, created_at timestamptz not null default now());
create table public.assessments (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, assessment_version_id uuid not null references public.assessment_versions(id), status text not null check(status in('started','completed','abandoned')), started_at timestamptz not null default now(), completed_at timestamptz);
create index assessments_owner_time_idx on public.assessments(user_id,started_at desc);
create table public.assessment_responses (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, assessment_id uuid not null references public.assessments(id) on delete cascade, question_key text not null, response_text text, response_number numeric, response_boolean boolean, response_unit text, created_at timestamptz not null default now(), unique(assessment_id,question_key));
create table public.body_measurements (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, measurement_type text not null, value numeric not null, unit text not null, measured_at timestamptz not null, created_at timestamptz not null default now());
create index body_measurements_owner_time_idx on public.body_measurements(user_id,measured_at desc);

create table public.exercises (id uuid primary key default gen_random_uuid(), slug text not null unique, name text not null, status text not null default 'draft', created_at timestamptz not null default now());
create table public.exercise_variants (id uuid primary key default gen_random_uuid(), exercise_id uuid not null references public.exercises(id) on delete cascade, name text not null, created_at timestamptz not null default now());
create table public.exercise_equipment (exercise_id uuid not null references public.exercises(id) on delete cascade, equipment_key text not null, primary key(exercise_id,equipment_key));
create table public.exercise_muscles (exercise_id uuid not null references public.exercises(id) on delete cascade, muscle_key text not null, role text not null check(role in('primary','secondary')), primary key(exercise_id,muscle_key,role));
create table public.exercise_constraints (id uuid primary key default gen_random_uuid(), exercise_id uuid not null references public.exercises(id) on delete cascade, constraint_key text not null, guidance text not null);
create table public.exercise_substitutions (exercise_id uuid not null references public.exercises(id) on delete cascade, substitute_exercise_id uuid not null references public.exercises(id) on delete cascade, reason_code text not null, primary key(exercise_id,substitute_exercise_id));

create table public.programs (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, goal_id uuid references public.goals(id), name text not null, engine_version text not null, ruleset_version text not null, prescribed_at timestamptz not null default now(), retired_at timestamptz);
create index programs_owner_history_idx on public.programs(user_id,prescribed_at desc);
create table public.program_phases (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, program_id uuid not null references public.programs(id) on delete cascade, sequence smallint not null, name text not null, unique(program_id,sequence));
create table public.program_weeks (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, phase_id uuid not null references public.program_phases(id) on delete cascade, sequence smallint not null, unique(phase_id,sequence));
create table public.program_workouts (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, program_week_id uuid not null references public.program_weeks(id) on delete cascade, sequence smallint not null, name text not null, unique(program_week_id,sequence));
create table public.workout_exercises (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, program_workout_id uuid not null references public.program_workouts(id) on delete cascade, exercise_id uuid not null references public.exercises(id), sequence smallint not null, unique(program_workout_id,sequence));
create table public.exercise_prescriptions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, workout_exercise_id uuid not null references public.workout_exercises(id) on delete cascade, sets smallint not null, rep_min smallint, rep_max smallint, load_value numeric, load_unit text, effort_target numeric, prescribed_at timestamptz not null default now(), supersedes_id uuid references public.exercise_prescriptions(id));

create table public.workout_sessions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, program_workout_id uuid references public.program_workouts(id), started_at timestamptz not null, completed_at timestamptz, time_zone text not null);
create index workout_sessions_owner_time_idx on public.workout_sessions(user_id,started_at desc);
create table public.exercise_sessions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, workout_session_id uuid not null references public.workout_sessions(id) on delete cascade, exercise_id uuid not null references public.exercises(id), sequence smallint not null);
create table public.sets (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, exercise_session_id uuid not null references public.exercise_sessions(id) on delete cascade, sequence smallint not null, reps smallint, load_value numeric, load_unit text, effort_actual numeric, completed_at timestamptz);
create table public.nutrition_targets (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, calories_kcal integer, protein_g numeric, carbohydrate_g numeric, fat_g numeric, fiber_g numeric, effective_from date not null, effective_to date, reason_code text not null, engine_version text not null, ruleset_version text not null, created_at timestamptz not null default now());
create index nutrition_targets_owner_history_idx on public.nutrition_targets(user_id,effective_from desc);
create table public.coach_decisions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, decision_type text not null, reason_code text not null, prior_state jsonb, new_state jsonb, structured_inputs jsonb not null default '{}'::jsonb, engine_version text not null, ruleset_version text not null, decided_at timestamptz not null default now());
create index coach_decisions_owner_time_idx on public.coach_decisions(user_id,decided_at desc);
create table public.safety_events (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, coach_decision_id uuid references public.coach_decisions(id), classification public.safety_classification not null, reason_codes text[] not null default '{}', engine_version text not null, ruleset_version text not null, evaluated_at timestamptz not null default now());
create index safety_events_owner_time_idx on public.safety_events(user_id,evaluated_at desc);

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path='' as $$ begin insert into public.profiles(user_id) values(new.id); return new; end $$;
revoke all on function public.handle_new_user() from public,anon,authenticated;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

do $$ declare t text; begin foreach t in array array['profiles','user_preferences','consents','subscriptions','subscription_events','entitlements','fitness_profiles','goals','assessments','assessment_responses','body_measurements','programs','program_phases','program_weeks','program_workouts','workout_exercises','exercise_prescriptions','workout_sessions','exercise_sessions','sets','nutrition_targets','coach_decisions','safety_events'] loop execute format('alter table public.%I enable row level security',t); execute format('create policy %I on public.%I for select to authenticated using ((select auth.uid()) = user_id)',t||'_select_own',t); execute format('create policy %I on public.%I for insert to authenticated with check ((select auth.uid()) = user_id)',t||'_insert_own',t); execute format('create policy %I on public.%I for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id)',t||'_update_own',t); execute format('create policy %I on public.%I for delete to authenticated using ((select auth.uid()) = user_id)',t||'_delete_own',t); end loop; end $$;
do $$ declare t text; begin foreach t in array array['assessment_versions','exercises','exercise_variants','exercise_equipment','exercise_muscles','exercise_constraints','exercise_substitutions'] loop execute format('alter table public.%I enable row level security',t); execute format('create policy %I on public.%I for select to anon,authenticated using (true)',t||'_read',t); end loop; end $$;
