import type{Exercise,Equipment,ExerciseRole,MovementPattern,Muscle}from"./types";
type Seed={slug:string;name:string;family:string;pattern:MovementPattern;role:ExerciseRole;primary:Muscle[];secondary?:Muscle[];equipment:Equipment[];skill?:Exercise["skill"];fatigue?:Exercise["fatigueCost"];reps?:[number,number];progression?:Exercise["progressionSuitability"];unilateral?:boolean;caution?:string[]};
const seeds:Seed[]=[
 {slug:"barbell-back-squat",name:"Barbell Back Squat",family:"squat",pattern:"squat",role:"primary",primary:["quadriceps","glutes"],secondary:["core"],equipment:["barbell"],skill:"intermediate",fatigue:5,caution:["reported_knee_or_back_discomfort"]},
 {slug:"goblet-squat",name:"Goblet Squat",family:"squat",pattern:"squat",role:"primary",primary:["quadriceps","glutes"],secondary:["core"],equipment:["dumbbells"],fatigue:3},
 {slug:"leg-press",name:"Leg Press",family:"squat",pattern:"squat",role:"primary",primary:["quadriceps","glutes"],equipment:["machines"],fatigue:3},
 {slug:"split-squat",name:"Dumbbell Split Squat",family:"lunge",pattern:"lunge",role:"secondary",primary:["quadriceps","glutes"],equipment:["dumbbells"],unilateral:true,fatigue:3},
 {slug:"barbell-rdl",name:"Barbell Romanian Deadlift",family:"hinge",pattern:"hinge",role:"primary",primary:["hamstrings","glutes"],secondary:["back"],equipment:["barbell"],skill:"intermediate",fatigue:4,caution:["reported_back_discomfort"]},
 {slug:"dumbbell-rdl",name:"Dumbbell Romanian Deadlift",family:"hinge",pattern:"hinge",role:"primary",primary:["hamstrings","glutes"],equipment:["dumbbells"],fatigue:3},
 {slug:"hip-thrust",name:"Hip Thrust",family:"hip_extension",pattern:"hinge",role:"secondary",primary:["glutes"],secondary:["hamstrings"],equipment:["barbell","bench"],fatigue:3},
 {slug:"leg-curl",name:"Leg Curl",family:"knee_flexion",pattern:"isolation",role:"accessory",primary:["hamstrings"],equipment:["machines"],fatigue:1},
 {slug:"barbell-bench-press",name:"Barbell Bench Press",family:"bench_press",pattern:"horizontal_push",role:"primary",primary:["chest"],secondary:["shoulders","triceps"],equipment:["barbell","bench"],skill:"intermediate",fatigue:4},
 {slug:"dumbbell-bench-press",name:"Dumbbell Bench Press",family:"bench_press",pattern:"horizontal_push",role:"primary",primary:["chest"],secondary:["shoulders","triceps"],equipment:["dumbbells","bench"],fatigue:3},
 {slug:"push-up",name:"Push-Up",family:"push_up",pattern:"horizontal_push",role:"primary",primary:["chest"],secondary:["shoulders","triceps","core"],equipment:["bodyweight"],fatigue:2},
 {slug:"dumbbell-overhead-press",name:"Dumbbell Overhead Press",family:"overhead_press",pattern:"vertical_push",role:"secondary",primary:["shoulders"],secondary:["triceps"],equipment:["dumbbells"],fatigue:3},
 {slug:"cable-row",name:"Seated Cable Row",family:"row",pattern:"horizontal_pull",role:"primary",primary:["back"],secondary:["biceps"],equipment:["cables"],fatigue:2},
 {slug:"one-arm-dumbbell-row",name:"One-Arm Dumbbell Row",family:"row",pattern:"horizontal_pull",role:"primary",primary:["back"],secondary:["biceps"],equipment:["dumbbells"],unilateral:true,fatigue:3},
 {slug:"lat-pulldown",name:"Lat Pulldown",family:"vertical_pull",pattern:"vertical_pull",role:"primary",primary:["back"],secondary:["biceps"],equipment:["cables"],fatigue:2},
 {slug:"pull-up",name:"Pull-Up",family:"vertical_pull",pattern:"vertical_pull",role:"primary",primary:["back"],secondary:["biceps"],equipment:["bodyweight"],skill:"intermediate",fatigue:3},
 {slug:"lateral-raise",name:"Dumbbell Lateral Raise",family:"lateral_raise",pattern:"isolation",role:"accessory",primary:["shoulders"],equipment:["dumbbells"],fatigue:1},
 {slug:"dumbbell-curl",name:"Dumbbell Curl",family:"elbow_flexion",pattern:"isolation",role:"accessory",primary:["biceps"],equipment:["dumbbells"],fatigue:1},
 {slug:"cable-triceps-pressdown",name:"Cable Triceps Pressdown",family:"elbow_extension",pattern:"isolation",role:"accessory",primary:["triceps"],equipment:["cables"],fatigue:1},
 {slug:"standing-calf-raise",name:"Standing Calf Raise",family:"calf_raise",pattern:"isolation",role:"accessory",primary:["calves"],equipment:["bodyweight"],fatigue:1},
];
export const exerciseLibrary:Exercise[]=seeds.map(s=>({slug:s.slug,name:s.name,family:s.family,pattern:s.pattern,role:s.role,primaryMuscles:s.primary,secondaryMuscles:s.secondary??[],requiredEquipment:s.equipment,skill:s.skill??"beginner",fatigueCost:s.fatigue??2,setupMinutes:s.role==="primary"?3:2,repRange:s.reps??(s.role==="accessory"?[10,20]:[5,15]),progressionSuitability:s.progression??4,unilateral:s.unilateral??false,instructions:[`Set up for the ${s.name} with a stable position.`,`Use a controlled range of motion you can repeat consistently.`,`Complete each rep without changing the intended movement pattern.`],cues:["Control the lowering phase.","Keep the working joints aligned.","Stop the set if technique materially changes."],mistakes:["Using load that shortens the intended range.","Rushing setup or losing position."],cautionTags:s.caution??[],reviewStatus:"reviewed",contentVersion:"1.0.0",license:"STHENO_ORIGINAL"}));
export function validateExercise(exercise:Exercise){const errors:string[]=[];if(!exercise.slug||!exercise.name)errors.push("identity");if(!exercise.primaryMuscles.length)errors.push("primary_muscle");if(!exercise.requiredEquipment.length)errors.push("equipment");if(exercise.instructions.length<3||exercise.cues.length<2||exercise.mistakes.length<1)errors.push("education");if(exercise.reviewStatus!=="reviewed")errors.push("review_status");return errors}
export const productionExerciseLibrary=exerciseLibrary.filter(e=>validateExercise(e).length===0);
