import{createHash}from"node:crypto";import{methodology,TRAINING_ENGINE_VERSION,TRAINING_RULESET_VERSION}from"./methodology";import{selectExercise}from"./selection";import type{ExerciseRole,MovementPattern,Prescription,TrainingProfile,TrainingProgram,Workout}from"./types";
const splits:Record<number,{name:string;focus:string;patterns:MovementPattern[]}[]>={
 2:[{name:"Full Body A",focus:"full_body",patterns:["squat","horizontal_push","horizontal_pull","hinge","isolation"]},{name:"Full Body B",focus:"full_body",patterns:["hinge","vertical_push","vertical_pull","lunge","isolation"]}],
 3:[{name:"Full Body A",focus:"full_body",patterns:["squat","horizontal_push","horizontal_pull","isolation"]},{name:"Full Body B",focus:"full_body",patterns:["hinge","vertical_push","vertical_pull","lunge"]},{name:"Full Body C",focus:"full_body",patterns:["lunge","horizontal_push","horizontal_pull","hinge","isolation"]}],
 4:[{name:"Upper A",focus:"upper",patterns:["horizontal_push","horizontal_pull","vertical_push","vertical_pull","isolation"]},{name:"Lower A",focus:"lower",patterns:["squat","hinge","lunge","isolation"]},{name:"Upper B",focus:"upper",patterns:["vertical_push","vertical_pull","horizontal_push","horizontal_pull","isolation"]},{name:"Lower B",focus:"lower",patterns:["hinge","squat","lunge","isolation"]}],
 5:[{name:"Upper Strength",focus:"upper",patterns:["horizontal_push","horizontal_pull","vertical_push","vertical_pull"]},{name:"Lower Strength",focus:"lower",patterns:["squat","hinge","lunge","isolation"]},{name:"Push",focus:"push",patterns:["horizontal_push","vertical_push","isolation"]},{name:"Pull",focus:"pull",patterns:["horizontal_pull","vertical_pull","isolation"]},{name:"Lower Hypertrophy",focus:"lower",patterns:["lunge","hinge","squat","isolation"]}],
};
function roleFor(index:number):ExerciseRole{return index===0?"primary":index<3?"secondary":"accessory"}
function makePrescription(profile:TrainingProfile,pattern:MovementPattern,index:number,used:string[]):Prescription{const role=roleFor(index);const selected=selectExercise({profile,pattern,role,usedSlugs:used});const reps=methodology.goalRepRanges[profile.goal][role];return{exerciseSlug:selected.exercise.slug,exerciseName:selected.exercise.name,role,sets:methodology.sets[profile.experience][role],repMin:reps[0],repMax:reps[1],rir:methodology.rir[profile.experience],restSeconds:methodology.rest[role],estimatedMinutes:methodology.session.exerciseMinutes[role],reasonCodes:selected.reasonCodes,alternatives:selected.alternatives}}
export function generateProgram(profile:TrainingProfile):TrainingProgram{if(profile.safetyClassification==="stop"||profile.safetyClassification==="refer")throw new Error("SAFETY_CLEARANCE_REQUIRED");if(profile.daysPerWeek<2||profile.daysPerWeek>5)throw new Error("UNSUPPORTED_FREQUENCY");if(profile.sessionMinutes<25)throw new Error("SESSION_TOO_SHORT");if(!profile.equipment.length)throw new Error("EQUIPMENT_REQUIRED");const template=splits[profile.daysPerWeek];const workouts:Workout[]=template.map((day,dayIndex)=>{const used:string[]=[];const exercises:Prescription[]=[];for(const pattern of day.patterns){const role=roleFor(exercises.length);const minutes=exercises.reduce((sum,e)=>sum+e.estimatedMinutes,methodology.session.bufferMinutes);if(minutes+methodology.session.exerciseMinutes[role]>profile.sessionMinutes)break;try{const item=makePrescription(profile,pattern,exercises.length,used);used.push(item.exerciseSlug);exercises.push(item)}catch(error){if(!String(error).includes("NO_ELIGIBLE_EXERCISE"))throw error}}if(exercises.length<3)throw new Error(`INSUFFICIENT_EXERCISE_COVERAGE:${day.name}`);return{key:`day-${dayIndex+1}`,name:day.name,dayOrdinal:dayIndex+1,focus:day.focus,estimatedMinutes:exercises.reduce((sum,e)=>sum+e.estimatedMinutes,methodology.session.bufferMinutes),exercises,reasonCodes:[`FREQUENCY_${profile.daysPerWeek}`,`FOCUS_${day.focus.toUpperCase()}`,profile.cardioDays&&profile.cardioDays>=3?"CONCURRENT_CARDIO_MANAGED":"SCHEDULE_HONORED"]}});const input=JSON.stringify({...profile,profileId:undefined,assessmentId:undefined});const id=createHash("sha256").update(`${TRAINING_RULESET_VERSION}:${input}`).digest("hex").slice(0,24);return{id,profileId:profile.profileId,assessmentId:profile.assessmentId,name:`${profile.daysPerWeek}-Day ${profile.goal.replaceAll("_"," ")} Foundation`,weeks:methodology.weeks,workouts,progressionPolicy:"double_progression",engineVersion:TRAINING_ENGINE_VERSION,rulesetVersion:TRAINING_RULESET_VERSION,generatedAt:new Date(0).toISOString(),reasonCodes:["PROFILE_VALIDATED","GOAL_RESOLVED","SCHEDULE_HONORED","EQUIPMENT_CONFIRMED","DETERMINISTIC_PRESCRIPTION"]}}
